name: CI

on:
  pull_request:
    branches:
      - homolog
      - main

  push:
    branches:
      - homolog

jobs:
  validate:
    name: Validate Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4